version: 2.1
setup: true

orbs:
  python: circleci/python@2.0.3
  continuation: circleci/continuation@0.1.2
  path-filtering: circleci/path-filtering@0.0.2

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            projects/python/.* python true
            projects/golang/.* golang true
            projects/csharp/.* csharp true
            projects/rust/.* rust true
            projects/nim/.* nimlang true
            .circleci/.* build-all true
          base-revision: master
          config-path: .circleci/test_langs.yml
